version: '3'
services:
  db:
    build:
      context: ./docker
#      dockerfile: Dockerfile-mariadb103
      dockerfile: Dockerfile-mysql56
#      dockerfile: Dockerfile-mysql57
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-utf8.cnf:/etc/mysql/conf.d/mysql-utf8.cnf
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      # MYSQL_DATABASE: unused_empty
      MYSQL_USER: coral_dbuser
      MYSQL_PASSWORD: where-is-the-coral-reef
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8181:80
  web:
    build:
      context: .
      # dockerfile: docker/Dockerfile-php56
      # dockerfile: docker/Dockerfile-php70
      # dockerfile: docker/Dockerfile-php71
      dockerfile: docker/Dockerfile-php72
    ports:
      - '8080:80'
    links:
      - db
    volumes:
      - ./coral:/var/www/html/coral
volumes:
#  mariadb103data:
  mysql56data:
#  mysql57data:
